# Configuration for 'in-memory' profile

# Disable JPA and H2 specific configurations for the in-memory profile
# as we are using manual InMemory_X_RepositoryImpl beans.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Explicitly clear datasource properties to prevent auto-configuration for a DB
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driverClassName=

# Disable H2 console for in-memory profile
spring.h2.console.enabled=false 