spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Define a default queue name
app.rabbitmq.queue.name=task.notifications.queue
# Define a default exchange name
app.rabbitmq.exchange.name=task.exchange
# Define a default routing key
app.rabbitmq.routing.key=task.created 